import type { AgeBand, Question, Subject } from "./school-data";

type ContentPack = Record<AgeBand, Record<Subject, Question[]>>;

export const curriculumMetadata = {
  id: "global-foundations-v1",
  title: "School Life Global Foundations",
  version: "1.0.0",
  status: "prototype-awaiting-expert-review",
  locale: "en",
  subjects: ["math", "reading", "science"] as Subject[],
  ageBands: ["early", "primary", "middle", "secondary", "university"] as AgeBand[],
  note: "A demonstration pack. Countries and schools should map objectives to their approved curriculum before formal classroom use.",
};

export const questionExtensions: ContentPack = {
  early: {
    math: [
      {
        id: "early-math-shapes",
        prompt: "Which shape has three sides?",
        answers: ["Circle", "Triangle", "Square"],
        correct: 1,
        hint: "Trace each side with your finger.",
        explanation: "A triangle has three straight sides and three corners.",
        objective: "Recognize common two-dimensional shapes.",
        difficulty: 1,
      },
      {
        id: "early-math-more",
        prompt: "Which group has more apples?",
        answers: ["🍎 🍎", "🍎 🍎 🍎 🍎", "🍎"],
        correct: 1,
        hint: "Count every apple in each group.",
        explanation: "Four apples are more than two apples or one apple.",
        objective: "Compare small quantities.",
        difficulty: 1,
      },
      {
        id: "early-math-add",
        prompt: "You have 2 blocks and get 1 more. How many blocks now?",
        answers: ["2", "3", "4"],
        correct: 1,
        hint: "Start at two and count one more.",
        explanation: "Two blocks plus one block makes three blocks.",
        objective: "Model addition within five.",
        difficulty: 2,
      },
    ],
    reading: [
      {
        id: "early-reading-rhyme",
        prompt: "Which word rhymes with cat?",
        answers: ["Hat", "Sun", "Dog"],
        correct: 0,
        hint: "Listen for the same ending sound.",
        explanation: "Cat and hat both end with the /at/ sound.",
        objective: "Recognize rhyme.",
        difficulty: 1,
      },
      {
        id: "early-reading-ending",
        prompt: "Which word ends with the /g/ sound?",
        answers: ["Dog", "Sun", "Map"],
        correct: 0,
        hint: "Stretch the final sound in each word.",
        explanation: "The last sound in dog is /g/.",
        objective: "Identify final sounds in spoken words.",
        difficulty: 2,
      },
      {
        id: "early-reading-word",
        prompt: "Choose the word that says sun.",
        answers: ["sun", "map", "cat"],
        correct: 0,
        hint: "Look for the word beginning with s.",
        explanation: "The letters s-u-n spell sun.",
        objective: "Recognize a familiar high-frequency word.",
        difficulty: 2,
      },
    ],
    science: [
      {
        id: "early-science-senses",
        prompt: "Which body part helps you hear music?",
        answers: ["Ears", "Elbows", "Knees"],
        correct: 0,
        hint: "Point to the part you use for listening.",
        explanation: "Our ears collect sounds so we can hear.",
        objective: "Connect senses with body parts.",
        difficulty: 1,
      },
      {
        id: "early-science-weather",
        prompt: "What should you carry on a rainy day?",
        answers: ["Umbrella", "Pillow", "Paintbrush"],
        correct: 0,
        hint: "Choose what helps keep you dry.",
        explanation: "An umbrella blocks falling rain.",
        objective: "Connect weather with appropriate choices.",
        difficulty: 1,
      },
      {
        id: "early-science-growth",
        prompt: "What does a seed need to begin growing?",
        answers: ["Water", "A toy", "A shoe"],
        correct: 0,
        hint: "Plants drink this through their roots.",
        explanation: "Water helps a seed germinate and begin growing.",
        objective: "Identify a basic need of plants.",
        difficulty: 2,
      },
    ],
  },
  primary: {
    math: [
      {
        id: "primary-math-perimeter",
        prompt: "A rectangle is 6 cm long and 3 cm wide. What is its perimeter?",
        answers: ["9 cm", "12 cm", "18 cm", "24 cm"],
        correct: 2,
        hint: "Add all four sides: 6 + 3 + 6 + 3.",
        explanation: "The perimeter is 6 + 3 + 6 + 3 = 18 cm.",
        objective: "Calculate perimeter of a rectangle.",
        difficulty: 2,
      },
      {
        id: "primary-math-decimal",
        prompt: "Which decimal is equal to three tenths?",
        answers: ["0.03", "0.3", "3.0", "30"],
        correct: 1,
        hint: "The first place after the decimal point is tenths.",
        explanation: "Three tenths is written as 0.3.",
        objective: "Connect fractions and decimals.",
        difficulty: 2,
      },
      {
        id: "primary-math-division",
        prompt: "Forty-two stickers are shared equally among 6 learners. How many does each receive?",
        answers: ["6", "7", "8", "9"],
        correct: 1,
        hint: "Find 42 ÷ 6.",
        explanation: "Because 6 × 7 = 42, each learner receives 7 stickers.",
        objective: "Solve an equal-sharing division problem.",
        difficulty: 2,
      },
    ],
    reading: [
      {
        id: "primary-reading-main-idea",
        prompt: "A paragraph describes how bees move pollen between flowers and help plants make seeds. What is its main idea?",
        answers: ["Bees help plants reproduce", "Flowers are always yellow", "Seeds can fly", "All insects make honey"],
        correct: 0,
        hint: "Choose the idea supported by the whole paragraph.",
        explanation: "Every detail explains how bees help flowering plants reproduce.",
        objective: "Identify a main idea.",
        difficulty: 2,
      },
      {
        id: "primary-reading-prefix",
        prompt: "What does the prefix re- mean in the word reread?",
        answers: ["Before", "Again", "Not", "Under"],
        correct: 1,
        hint: "If a page was unclear, you might read it one more time.",
        explanation: "The prefix re- means again, so reread means read again.",
        objective: "Use affixes to determine word meaning.",
        difficulty: 2,
      },
      {
        id: "primary-reading-cause",
        prompt: "The path was icy, so the caretaker spread salt. Which event is the cause?",
        answers: ["The path was icy", "The caretaker spread salt", "Morning arrived", "The gate opened"],
        correct: 0,
        hint: "Ask what made the caretaker take action.",
        explanation: "The icy path caused the caretaker to spread salt.",
        objective: "Identify cause and effect.",
        difficulty: 2,
      },
    ],
    science: [
      {
        id: "primary-science-evaporation",
        prompt: "A puddle becomes smaller on a warm day. What most likely happened?",
        answers: ["The water evaporated", "The water froze", "The water became soil", "The water stopped existing"],
        correct: 0,
        hint: "Heat can turn liquid water into water vapour.",
        explanation: "Warmth speeds evaporation, moving liquid water into the air as vapour.",
        objective: "Describe a change of state.",
        difficulty: 2,
      },
      {
        id: "primary-science-food-chain",
        prompt: "In grass → rabbit → fox, which organism is the producer?",
        answers: ["Grass", "Rabbit", "Fox", "All three"],
        correct: 0,
        hint: "The producer makes its own food using light.",
        explanation: "Grass is a plant and produces food through photosynthesis.",
        objective: "Identify roles in a food chain.",
        difficulty: 2,
      },
      {
        id: "primary-science-circuit",
        prompt: "What must a simple circuit have for a bulb to light?",
        answers: ["A complete path", "An open switch only", "A plastic gap", "Two disconnected wires"],
        correct: 0,
        hint: "Electric current needs an unbroken route.",
        explanation: "A complete, closed circuit lets current travel through the bulb.",
        objective: "Explain a complete electrical circuit.",
        difficulty: 3,
      },
    ],
  },
  middle: {
    math: [
      {
        id: "middle-math-ratio",
        prompt: "The ratio of red to blue flags is 3:5. If there are 15 red flags, how many blue flags are there?",
        answers: ["20", "25", "30", "35"],
        correct: 1,
        hint: "The scale factor from 3 to 15 is 5.",
        explanation: "Multiply both parts by 5: 3:5 becomes 15:25.",
        objective: "Solve proportional ratio problems.",
        difficulty: 2,
      },
      {
        id: "middle-math-percent",
        prompt: "A game costs 40 coins and is discounted by 25%. What is the new cost?",
        answers: ["10", "25", "30", "35"],
        correct: 2,
        hint: "Twenty-five percent is one quarter.",
        explanation: "One quarter of 40 is 10, so 40 − 10 = 30 coins.",
        objective: "Calculate a percentage decrease.",
        difficulty: 2,
      },
      {
        id: "middle-math-mean",
        prompt: "What is the mean of 6, 8, 9, 12 and 15?",
        answers: ["9", "10", "11", "12"],
        correct: 1,
        hint: "Add the five values, then divide by five.",
        explanation: "The total is 50, and 50 ÷ 5 = 10.",
        objective: "Calculate an arithmetic mean.",
        difficulty: 2,
      },
    ],
    reading: [
      {
        id: "middle-reading-thesis",
        prompt: "Which sentence works best as an argumentative thesis?",
        answers: ["School gardens are green.", "Schools should create gardens because they support science learning and wellbeing.", "I saw a garden.", "Gardens contain plants."],
        correct: 1,
        hint: "A thesis should make a clear, supportable claim.",
        explanation: "The sentence states a position and previews two reasons that can be supported.",
        objective: "Recognize an arguable thesis.",
        difficulty: 2,
      },
      {
        id: "middle-reading-tone",
        prompt: "Words such as bleak, silent and abandoned create which tone?",
        answers: ["Celebratory", "Gloomy", "Playful", "Formal"],
        correct: 1,
        hint: "Think about the feeling created by all three words.",
        explanation: "The words create a dark, lonely or gloomy tone.",
        objective: "Infer tone from word choice.",
        difficulty: 2,
      },
      {
        id: "middle-reading-evidence",
        prompt: "Which source is strongest for a report about local rainfall trends?",
        answers: ["A fictional story", "Ten years of meteorological records", "An anonymous comment", "A product advertisement"],
        correct: 1,
        hint: "Look for direct, measured and checkable evidence.",
        explanation: "Long-term meteorological records provide relevant measurements across time.",
        objective: "Evaluate source relevance and reliability.",
        difficulty: 3,
      },
    ],
    science: [
      {
        id: "middle-science-atoms",
        prompt: "Which particle determines an element’s atomic number?",
        answers: ["Proton", "Neutron", "Electron", "Photon"],
        correct: 0,
        hint: "This positively charged particle is in the nucleus.",
        explanation: "An element’s atomic number equals its number of protons.",
        objective: "Relate atomic structure to the periodic table.",
        difficulty: 2,
      },
      {
        id: "middle-science-density",
        prompt: "An object has a mass of 120 g and a volume of 40 cm³. What is its density?",
        answers: ["2 g/cm³", "3 g/cm³", "4 g/cm³", "80 g/cm³"],
        correct: 1,
        hint: "Density equals mass divided by volume.",
        explanation: "120 ÷ 40 = 3 g/cm³.",
        objective: "Calculate density.",
        difficulty: 2,
      },
      {
        id: "middle-science-ecosystem",
        prompt: "If a predator disappears from an ecosystem, its prey population will most likely initially…",
        answers: ["Increase", "Disappear immediately", "Become producers", "Stop reproducing"],
        correct: 0,
        hint: "Consider what happens when fewer prey are eaten.",
        explanation: "With less predation, more prey are likely to survive and reproduce initially.",
        objective: "Predict effects within a food web.",
        difficulty: 3,
      },
    ],
  },
  secondary: {
    math: [
      {
        id: "secondary-math-simultaneous",
        prompt: "Solve x + y = 10 and x − y = 4.",
        answers: ["x = 7, y = 3", "x = 6, y = 4", "x = 8, y = 2", "x = 5, y = 5"],
        correct: 0,
        hint: "Add the two equations to eliminate y.",
        explanation: "Adding gives 2x = 14, so x = 7 and y = 3.",
        objective: "Solve simultaneous linear equations.",
        difficulty: 2,
      },
      {
        id: "secondary-math-probability",
        prompt: "A fair die is rolled twice. What is the probability of rolling two sixes?",
        answers: ["1/6", "1/12", "1/36", "1/72"],
        correct: 2,
        hint: "Multiply the probability of each independent event.",
        explanation: "The probability is 1/6 × 1/6 = 1/36.",
        objective: "Calculate probability of independent events.",
        difficulty: 2,
      },
      {
        id: "secondary-math-exponential",
        prompt: "A population doubles every 3 hours. If it starts at 200, what is it after 9 hours?",
        answers: ["600", "800", "1,200", "1,600"],
        correct: 3,
        hint: "Nine hours contains three doubling periods.",
        explanation: "After three doublings: 200 × 2³ = 1,600.",
        objective: "Model exponential growth.",
        difficulty: 3,
      },
    ],
    reading: [
      {
        id: "secondary-reading-rhetoric",
        prompt: "A writer cites verified statistics and explains their source. Which rhetorical appeal is strongest?",
        answers: ["Logos", "Pathos", "Hyperbole", "Allusion"],
        correct: 0,
        hint: "This appeal relies on reasoning and evidence.",
        explanation: "Statistics and transparent reasoning primarily strengthen logos.",
        objective: "Analyze rhetorical appeals.",
        difficulty: 2,
      },
      {
        id: "secondary-reading-symbol",
        prompt: "A recurring locked door in a novel most plausibly functions as…",
        answers: ["A symbol of exclusion or hidden truth", "A spelling error", "A change of narrator", "An index entry"],
        correct: 0,
        hint: "Repeated concrete objects can carry abstract meaning.",
        explanation: "A locked door can symbolize barriers, secrecy or knowledge that cannot yet be reached.",
        objective: "Interpret literary symbolism.",
        difficulty: 2,
      },
      {
        id: "secondary-reading-source",
        prompt: "Which practice best verifies an online historical claim?",
        answers: ["Trust the first result", "Compare it with primary sources and reputable scholarship", "Count the page images", "Use only social-media reactions"],
        correct: 1,
        hint: "Verification requires independent, credible evidence.",
        explanation: "Triangulating primary evidence with reputable scholarship tests both accuracy and context.",
        objective: "Verify claims across sources.",
        difficulty: 3,
      },
    ],
    science: [
      {
        id: "secondary-science-ph",
        prompt: "A solution changes from pH 3 to pH 4. Its hydrogen-ion concentration becomes…",
        answers: ["Ten times greater", "Ten times smaller", "Twice as large", "Unchanged"],
        correct: 1,
        hint: "The pH scale is logarithmic.",
        explanation: "An increase of one pH unit means a tenfold decrease in hydrogen-ion concentration.",
        objective: "Interpret the logarithmic pH scale.",
        difficulty: 3,
      },
      {
        id: "secondary-science-resistance",
        prompt: "A 12 V supply produces a current of 3 A. What is the resistance?",
        answers: ["0.25 Ω", "4 Ω", "9 Ω", "36 Ω"],
        correct: 1,
        hint: "Use R = V ÷ I.",
        explanation: "12 ÷ 3 = 4 ohms.",
        objective: "Apply Ohm’s law.",
        difficulty: 2,
      },
      {
        id: "secondary-science-selection",
        prompt: "Natural selection directly acts on differences in…",
        answers: ["Heritable traits affecting reproductive success", "Traits acquired through practice only", "Every mutation equally", "An organism’s wishes"],
        correct: 0,
        hint: "The relevant differences must be inherited and affect offspring.",
        explanation: "Selection changes populations when heritable variation influences survival or reproduction.",
        objective: "Explain natural selection.",
        difficulty: 3,
      },
    ],
  },
  university: {
    math: [
      {
        id: "university-math-ci",
        prompt: "A narrower confidence interval, with confidence level held constant, most directly indicates…",
        answers: ["Greater estimate precision", "Guaranteed absence of bias", "A larger p-value", "Proof of causation"],
        correct: 0,
        hint: "Focus on the range of plausible parameter values.",
        explanation: "A narrower interval represents a more precise estimate, though it does not remove bias or prove causality.",
        objective: "Interpret confidence-interval precision.",
        difficulty: 2,
      },
      {
        id: "university-math-integral",
        prompt: "Evaluate ∫₀¹ 2x dx.",
        answers: ["0", "1", "2", "4"],
        correct: 1,
        hint: "An antiderivative of 2x is x².",
        explanation: "x² evaluated from 0 to 1 equals 1² − 0² = 1.",
        objective: "Evaluate a definite integral.",
        difficulty: 2,
      },
      {
        id: "university-math-correlation",
        prompt: "A correlation of r = −0.92 indicates…",
        answers: ["A strong negative linear association", "A weak positive association", "Proof that X causes Y", "No linear association"],
        correct: 0,
        hint: "Consider both the sign and magnitude.",
        explanation: "The magnitude is close to one and the sign is negative; correlation alone does not establish causation.",
        objective: "Interpret a correlation coefficient.",
        difficulty: 2,
      },
    ],
    reading: [
      {
        id: "university-reading-methods",
        prompt: "Which detail is most important when assessing whether a qualitative study is transferable?",
        answers: ["Thick description of context and participants", "The number of decorative figures", "A short reference list", "The author’s job title alone"],
        correct: 0,
        hint: "Readers need enough context to judge relevance elsewhere.",
        explanation: "Rich contextual description allows readers to judge whether findings may transfer to another setting.",
        objective: "Critically appraise qualitative research.",
        difficulty: 3,
      },
      {
        id: "university-reading-primary",
        prompt: "For research on a newly enacted law, which is the strongest primary source?",
        answers: ["The enacted statutory text", "An unsourced blog summary", "A fictional case", "A promotional poster"],
        correct: 0,
        hint: "A primary source is the original material being examined.",
        explanation: "The enacted text is the authoritative original legal instrument.",
        objective: "Distinguish primary and secondary sources.",
        difficulty: 2,
      },
      {
        id: "university-reading-synthesis",
        prompt: "Which paragraph structure demonstrates synthesis?",
        answers: ["It compares several studies around one claim and explains their differences", "It lists one abstract after another", "It repeats the research question", "It presents citations without interpretation"],
        correct: 0,
        hint: "Synthesis shows relationships among sources.",
        explanation: "Comparing evidence around a shared claim integrates sources rather than merely summarizing them.",
        objective: "Synthesize academic literature.",
        difficulty: 2,
      },
    ],
    science: [
      {
        id: "university-science-falsifiable",
        prompt: "A scientifically falsifiable hypothesis must…",
        answers: ["Make a prediction that evidence could contradict", "Be impossible to test", "Always be correct", "Contain no measurable variables"],
        correct: 0,
        hint: "Consider what result could show the claim is wrong.",
        explanation: "Falsifiability requires a conceivable observation that conflicts with the hypothesis.",
        objective: "Evaluate scientific hypotheses.",
        difficulty: 2,
      },
      {
        id: "university-science-validity",
        prompt: "Random assignment primarily strengthens a study’s…",
        answers: ["Internal validity", "Publication count", "Measurement units", "External validity in every population"],
        correct: 0,
        hint: "It helps balance confounding variables across conditions.",
        explanation: "Random assignment supports causal inference by reducing systematic group differences.",
        objective: "Evaluate experimental design.",
        difficulty: 2,
      },
      {
        id: "university-science-replication",
        prompt: "A direct replication is designed mainly to test whether…",
        answers: ["A result can be obtained again under closely matched methods", "A different question is more interesting", "The original authors agree", "The sample is always larger"],
        correct: 0,
        hint: "The key idea is repeatability under similar conditions.",
        explanation: "Direct replication repeats core methods to evaluate the reliability of an earlier result.",
        objective: "Explain the role of replication.",
        difficulty: 2,
      },
    ],
  },
};
